import type { Analysis } from '../analysis.js';
import { ROI_FORMULA } from '../roi/roi.js';
import { fmtDelta, fmtValue } from './format.js';

const STATUS: Record<string, string> = {
  new: 'NEW — introduced by this version',
  persisting: 'PERSISTING — also present in the baseline',
  resolved: 'RESOLVED',
};

export function renderBacklog(a: Analysis): string {
  const c = a.comparison;
  const audit = a.audits[a.backlog_variant];
  const L: string[] = [];
  L.push(`# ROI Backlog — ${a.backlog_variant}`);
  L.push('');
  L.push(
    `> Generated by Buyer Arena · session \`${a.session.session_id}\` · ${a.summaries[0]?.n ?? 0} synthetic buyers × ${a.variants.length} variant(s) · buyer policy \`${a.session.buyer}\` · auditors \`${audit?.auditor_mode ?? 'deterministic'}\``,
  );
  L.push('>');
  L.push(
    `> **CONVERSION PROXY${c ? ` · ${c.label}` : ''}.** Scores rank synthetic evidence; they are not predicted revenue. No monetary ROI is claimed without real revenue data.`,
  );
  L.push('');

  if (c) {
    L.push('## Headline');
    L.push('');
    L.push(`| Metric | ${c.baseline} | ${c.candidate} | Delta | 95% interval |`);
    L.push('|---|---:|---:|---:|---:|');
    for (const r of c.rows) {
      L.push(
        `| ${r.metric} | ${fmtValue(r.baseline, r.unit)} | ${fmtValue(r.candidate, r.unit)} | ${fmtDelta(r.delta, r.unit)} | ${r.ci ? `${fmtDelta(r.ci[0], r.unit)} … ${fmtDelta(r.ci[1], r.unit)}` : '—'} |`,
      );
    }
    L.push('');
  }

  L.push('## Ranked experiments');
  L.push('');
  if (a.backlog.length === 0) L.push('_No actionable friction with evidence was found._');
  for (const o of a.backlog) {
    const item = audit?.consensus.find((x) => x.id === o.id);
    L.push(`### #${o.rank} ${o.title} — ${o.leverage}`);
    L.push('');
    L.push(
      `- **Finding:** ${o.id} · score **${o.score}**${o.status ? ` · ${STATUS[o.status] ?? o.status}` : ''}`,
    );
    L.push(
      `- **Evidence:** ${o.affected} buyers affected · ${o.evidence_ids.map((e) => `\`${e}\``).join(', ')}`,
    );
    if (item) {
      L.push(`- **Observed fact:** ${item.observed_fact}`);
      L.push(
        `- **${item.claim === 'inference' ? 'Inference' : 'Hypothesis'}:** ${item.interpretation.replace(/^Likely cause \([a-z]+\): /, '')}`,
      );
      if (item.counterfactual) L.push(`- **Counterfactual:** ${item.counterfactual}`);
      L.push(`- **Independent sources:** ${item.sources.join(', ')}`);
      L.push(
        `- **Auditors in support:** ${item.supporters.join(', ')}${item.challenges.length ? ` · **challenged by red team:** ${item.challenges.map((x) => x.text).join(' / ')}` : ''}`,
      );
    }
    L.push(
      `- **Confidence:** ${item?.confidence ?? '—'} · **Effort:** ${o.factors.effort} · **Reversibility:** ${o.factors.reversibility} · **Testability:** ${o.factors.testability}`,
    );
    L.push(
      `- **If fixed:** up to +${Math.round(o.ceiling_pp * 100)}pp goal completion (journeys that ended at this friction)`,
    );
    L.push(`- **Suggested experiment:** ${o.experiment}`);
    L.push('');
  }

  if (a.resolved.length && c) {
    L.push(`## Resolved by ${c.candidate}`);
    L.push('');
    L.push(`| Friction | ${c.baseline} (affected) | ${c.candidate} (affected) |`);
    L.push('|---|---:|---:|');
    for (const r of a.resolved) L.push(`| ${r.title} | ${r.baseline_affected} | 0 |`);
    L.push('');
  }

  L.push('## How the score works');
  L.push('');
  L.push('```');
  L.push(ROI_FORMULA);
  L.push('```');
  L.push('');
  L.push(
    '- `frequency` = affected buyers / population · `goal_impact` = affected buyers whose journey ENDED at this friction / affected',
  );
  L.push(
    '- `frequency × goal_impact` is the "if fixed" ceiling; the score is that ceiling in pp, weighted by confidence and ease of testing, per unit of effort',
  );
  L.push(
    '- `confidence` low .4 · medium .7 · high 1 (lowered by red-team challenges) · `effort_cost` low 1 · medium 2 · high 4 (playbook defaults; override per team)',
  );
  L.push('- Labels: ≥5 HIGH-LEVERAGE EXPERIMENT · ≥2 MEDIUM · otherwise LOW');
  L.push('');
  if (c) {
    L.push('## Caveats');
    L.push('');
    for (const x of c.caveats) L.push(`- ${x}`);
    L.push('');
  }
  return L.join('\n');
}
