import { existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { Analysis } from '../analysis.js';
import { readJson } from '../core/fs.js';
import type { Persona, RunRecord, Story } from '../core/types.js';
import { ROI_FORMULA } from '../roi/roi.js';
import { runDir } from '../simulator/session.js';

interface JourneyView {
  run_id: string;
  variant: string;
  persona_id: string;
  name: string;
  segment: string;
  archetype: string;
  device: string;
  budget: string;
  status: string;
  completed: boolean;
  steps: number;
  abandon_reason?: string;
  objection?: string;
  milestones: string[];
  trace?: string;
  story?: string;
  policy: string;
  usage?: RunRecord['usage'];
  events: {
    id: string;
    step: number;
    type: string;
    target?: string;
    detail?: string;
    shot?: string;
    url: string;
  }[];
}

const SKIP = new Set(['observe']);

/** Build the explorer model. Screenshots are referenced relative to the report file. */
export function journeyViews(sessionDir: string, runs: RunRecord[], personas: Persona[]): JourneyView[] {
  return runs.map((r) => {
    const dir = runDir(sessionDir, r.variant, r.persona_id);
    const rel = relative(sessionDir, dir).split('\\').join('/');
    const storyFile = join(dir, 'story.json');
    const story = existsSync(storyFile) ? readJson<Story>(storyFile).narrative : undefined;
    const p = personas.find((x) => x.persona_id === r.persona_id);
    const shotByStep = new Map<number, string>();
    for (const e of r.events)
      if (e.type === 'observe' && e.screenshot && !shotByStep.has(e.step))
        shotByStep.set(e.step, `${rel}/${e.screenshot}`);
    return {
      run_id: r.run_id,
      variant: r.variant,
      persona_id: r.persona_id,
      name: p?.name ?? r.persona_id,
      segment: r.segment,
      archetype: r.archetype,
      device: p ? `${p.device.kind} ${p.device.viewport.width}×${p.device.viewport.height}` : '',
      budget: p ? `${p.budget} ${p.currency}/mo` : '',
      status: r.status,
      completed: r.goal_completed,
      steps: r.steps,
      abandon_reason: r.abandon_reason,
      objection: r.objection,
      milestones: Object.keys(r.milestones),
      trace: r.trace_path ? `${rel}/${r.trace_path}` : undefined,
      story,
      policy: r.policy,
      usage: r.usage,
      events: r.events
        .filter((e) => !SKIP.has(e.type) || shotByStep.get(e.step) === `${rel}/${e.screenshot}`)
        .map((e) => ({
          id: e.id,
          step: e.step,
          type: e.type,
          target: e.target,
          detail: e.detail,
          shot: e.screenshot ? `${rel}/${e.screenshot}` : undefined,
          url: (() => {
            try {
              const u = new URL(e.url);
              return u.pathname + u.search;
            } catch {
              return e.url;
            }
          })(),
        })),
    };
  });
}

const esc = (s: string) => s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

export function renderReport(a: Analysis, journeys: JourneyView[]): string {
  const segments = new Set(a.metrics.map((m) => m.segment)).size;
  const buyers = a.summaries[0]?.n ?? 0;
  const data = {
    meta: {
      session: a.session.session_id,
      generated: a.generated_at,
      buyer: a.session.buyer,
      template: a.session.template,
      seed: a.session.seed,
      variants: a.session.variants,
      buyers,
      segments,
      formula: ROI_FORMULA,
      usage: a.session.usage,
      auditor_mode: a.audits[a.backlog_variant]?.auditor_mode ?? 'deterministic',
    },
    summaries: a.summaries,
    comparison: a.comparison,
    clusters: a.clusters.map((c) => ({ ...c, evidence_ids: c.evidence_ids.slice(0, 24) })),
    audits: a.audits,
    backlog: a.backlog,
    backlog_variant: a.backlog_variant,
    resolved: a.resolved,
    journeys,
  };
  const json = JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/\u2028|\u2029/g, '');
  const title = a.comparison ? `${a.comparison.baseline} → ${a.comparison.candidate}` : a.variants.join(', ');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Buyer Arena · ${esc(title)}</title>
<meta name="description" content="Synthetic customer simulation report generated by Buyer Arena.">
<style>${CSS}</style></head>
<body>
<header class="top"><div class="wrap row">
  <div class="brand"><span class="mark">▲</span> BUYER ARENA <span class="dim">/ synthetic customer simulation</span></div>
  <div class="meta mono" id="meta"></div>
</div></header>
<main class="wrap">
  <section class="hero" id="hero"></section>
  <section id="kpis" class="kpis"></section>
  <section class="grid2">
    <div class="panel"><h2>Funnel reach</h2><div id="funnel"></div><p class="note">Share of buyers who reached each stage (or any later stage).</p></div>
    <div class="panel"><h2>Segments</h2><div id="segments"></div></div>
  </section>
  <section class="panel"><div class="row between"><h2>Top friction</h2><div class="tabs" id="frictionTabs"></div></div><div id="friction"></div></section>
  <section class="panel"><div class="row between"><h2>Recommended experiments</h2><span class="chip">ROI backlog · <span id="blv"></span></span></div><div id="backlog"></div>
    <details class="formula"><summary>Scoring formula</summary><code id="formula"></code></details></section>
  <section class="panel"><div class="row between"><h2>Five independent auditors → consensus</h2><div class="tabs" id="auditTabs"></div></div><div id="auditors" class="auditors"></div><div id="consensus"></div></section>
  <section class="panel" id="explorer"><div class="row between"><h2>Journey explorer</h2><div class="legend mono"><i class="ok"></i>completed <i class="ab"></i>abandoned <i class="lim"></i>limit/timeout <i class="err"></i>error</div></div>
    <div class="explorer"><div id="roster" class="roster"></div><div id="journey" class="journey"><p class="dim">Select a buyer — or click any evidence id — to replay the journey.</p></div></div></section>
  <section class="panel"><h2>Method &amp; caveats</h2><ul id="caveats" class="caveats"></ul></section>
  <footer class="foot mono dim">Generated by Buyer Arena · synthetic buyers only · no real customer data · results are a conversion proxy, not predicted revenue.</footer>
</main>
<div id="lightbox" class="lightbox" hidden><img alt="Journey screenshot"></div>
<script id="data" type="application/json">${json}</script>
<script>${CLIENT}</script>
</body></html>`;
}

const CSS = `
:root{--bg:#090c10;--panel:#0f141a;--panel2:#131a22;--line:#1f2933;--text:#d9e2ec;--muted:#7b8a9a;--dim:#56636f;--base:#93a4b8;--cand:#4fe0c0;--good:#4fe08f;--bad:#ff6b6b;--warn:#ffb454;--info:#7aa7ff;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace;--sans:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
*{box-sizing:border-box}html,body{margin:0;overflow-x:hidden;background:var(--bg);color:var(--text);font:14px/1.5 var(--sans)}
a{color:var(--cand)}.wrap{max-width:1240px;margin:0 auto;padding:0 20px}.row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.between{justify-content:space-between}
.mono{font-family:var(--mono)}.dim{color:var(--muted)}h2{font:600 12px/1 var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin:0 0 14px}
.top{border-bottom:1px solid var(--line);background:linear-gradient(180deg,#0c1117,#090c10);position:sticky;top:0;z-index:5}.top .row{height:52px;justify-content:space-between}
.brand{font:700 14px var(--mono);letter-spacing:.22em}.brand .mark{color:var(--cand)}.brand .dim{letter-spacing:.04em;font-weight:400;font-size:12px}.meta{font-size:11px;color:var(--dim)}
.hero{padding:34px 0 18px;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr);gap:24px;align-items:end}
.hero .count{font:700 clamp(24px,3vw,40px)/1.1 var(--mono);letter-spacing:.02em}.hero .count b{color:var(--cand)}.hero .count span{color:var(--dim)}
.hero .vs{font:600 15px var(--mono);letter-spacing:.18em;margin-top:12px;color:var(--muted)}.hero .vs .b{color:var(--base)}.hero .vs .c{color:var(--cand)}
.headline{border:1px solid var(--line);background:var(--panel);border-radius:10px;padding:18px 20px}.headline .big{font:700 42px/1 var(--mono);color:var(--good)}.headline .big.neg{color:var(--bad)}
.badge{display:inline-block;font:700 10px/1 var(--mono);letter-spacing:.14em;padding:6px 8px;border-radius:4px;border:1px solid var(--warn);color:var(--warn);margin-right:6px}.badge.proxy{border-color:var(--info);color:var(--info)}
.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:10px 0 18px}.kpi{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 14px 12px}
.kpi .l{font:600 10px var(--mono);letter-spacing:.14em;color:var(--muted);text-transform:uppercase}.kpi .v{font:600 20px var(--mono);margin:8px 0 2px;white-space:nowrap}.kpi .v .b{color:var(--base)}.kpi .v .arrow{color:var(--dim);font-size:14px;margin:0 4px}
.kpi .d{font:700 13px var(--mono)}.good{color:var(--good)}.bad{color:var(--bad)}.flat{color:var(--muted)}.kpi .ci{font:11px var(--mono);color:var(--dim)}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:18px 18px 16px;margin:0 0 16px}.grid2{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.grid2 .panel{margin:0 0 16px}
.note{color:var(--dim);font-size:12px;margin:10px 0 0}
.fun{display:grid;grid-template-columns:130px 1fr 44px;gap:8px;align-items:center;margin:6px 0;font:12px var(--mono)}.fun .bars{display:grid;gap:3px}.bar{height:9px;border-radius:2px;background:var(--line);position:relative;overflow:hidden}.bar i{position:absolute;inset:0 auto 0 0;border-radius:2px}
.bar i.b{background:var(--base)}.bar i.c{background:var(--cand)}.fun .n{text-align:right;color:var(--muted);font-size:11px;line-height:12px}
table{width:100%;border-collapse:collapse;font-size:13px}th{font:600 10px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--muted);text-align:left;padding:8px 6px;border-bottom:1px solid var(--line)}
td{padding:8px 6px;border-bottom:1px solid #161d25;vertical-align:top}td.num{font-family:var(--mono);text-align:right;white-space:nowrap}
.tabs{display:flex;gap:6px}.tab{font:600 11px var(--mono);letter-spacing:.08em;padding:6px 10px;border:1px solid var(--line);background:transparent;color:var(--muted);border-radius:6px;cursor:pointer}.tab.on{color:var(--text);border-color:var(--cand)}
.fr{display:grid;grid-template-columns:minmax(0,1fr) 170px;gap:14px;padding:12px 0;border-bottom:1px solid #161d25}.fr:last-child{border:0}.fr h3{margin:0 0 4px;font-size:15px}
.fr .ex{color:var(--muted);font-size:12px;margin:4px 0}.meter{font:12px var(--mono);text-align:right}.meter .bar{height:7px;margin-top:6px}.meter .bar i{background:var(--warn)}
.chip{display:inline-block;font:600 10px/1 var(--mono);letter-spacing:.06em;padding:5px 7px;border-radius:4px;border:1px solid var(--line);color:var(--muted);margin:2px 4px 2px 0;white-space:nowrap}
.chip.new{border-color:var(--bad);color:var(--bad)}.chip.persisting{border-color:var(--warn);color:var(--warn)}.chip.resolved{border-color:var(--good);color:var(--good)}
.chip.fact{border-color:var(--info);color:var(--info)}.chip.inference{border-color:var(--cand);color:var(--cand)}.chip.hypothesis{border-color:var(--warn);color:var(--warn)}
.chip.high,.chip.critical{border-color:var(--bad);color:var(--bad)}.chip.medium{border-color:var(--warn);color:var(--warn)}
.ev{font:11px var(--mono);color:var(--cand);background:#0c1a17;border:1px solid #183a33;border-radius:4px;padding:2px 5px;margin:2px 3px 2px 0;display:inline-block;cursor:pointer;text-decoration:none}.ev:hover{border-color:var(--cand)}
.bl{display:grid;grid-template-columns:44px minmax(0,1fr) 150px;gap:14px;padding:14px 0;border-bottom:1px solid #161d25}.bl:last-child{border:0}.bl .rk{font:700 22px var(--mono);color:var(--dim)}.bl h3{margin:0 0 6px;font-size:15px}
.bl .sc{text-align:right;font:12px var(--mono)}.bl .sc b{display:block;font-size:22px;color:var(--text)}.lev{font:700 10px var(--mono);letter-spacing:.1em}.lev.HIGH-LEVERAGE{color:var(--good)}.lev.MEDIUM{color:var(--warn)}.lev.LOW{color:var(--muted)}
.bl .exp{margin:6px 0 0;color:var(--text)}.bl .fx{font:11px var(--mono);color:var(--dim);margin-top:6px}
details.formula{margin-top:10px;color:var(--muted);font-size:12px}details.formula code{display:block;margin-top:8px;font:12px var(--mono);color:var(--text);white-space:pre-wrap}
.auditors{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:16px}.aud{background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:12px}.aud .n{font:700 24px var(--mono)}.aud .t{font:600 11px var(--mono);letter-spacing:.08em;text-transform:uppercase}.aud p{color:var(--muted);font-size:12px;margin:6px 0 0}.aud.red{border-color:#3a2226}.aud .deg{color:var(--warn);font:11px var(--mono)}
.cs{border-top:1px solid #161d25;padding:12px 0}.cs h3{margin:0 0 6px;font-size:14px}.cs .fact{margin:4px 0}.cs .interp{color:var(--muted);margin:4px 0}.cs .chal{border-left:2px solid var(--bad);padding:4px 10px;margin:8px 0 4px;color:#e9b6b6;font-size:12px}
.explorer{display:grid;grid-template-columns:330px minmax(0,1fr);gap:16px;min-height:520px}.roster{max-height:760px;overflow:auto;border-right:1px solid var(--line);padding-right:10px}
.rr{display:grid;grid-template-columns:1fr 64px 64px;gap:6px;align-items:center;padding:5px 4px;border-bottom:1px solid #141b22;font-size:12px}.rr .who b{display:block;font-weight:600}.rr .who span{color:var(--dim);font-size:11px}
.rr button{font:600 10px var(--mono);border-radius:4px;border:1px solid var(--line);padding:5px 0;cursor:pointer;background:var(--panel2);color:var(--text)}.rr button.sel{outline:2px solid var(--text)}
.st-completed{border-color:#1f5a3f!important;color:var(--good)!important}.st-abandoned{border-color:#5a2a2a!important;color:var(--bad)!important}.st-step_limit,.st-timeout{border-color:#5a4520!important;color:var(--warn)!important}.st-error,.st-budget_exhausted{border-color:#44325a!important;color:#c49bff!important}
.rh{display:grid;grid-template-columns:1fr 64px 64px;gap:6px;font:600 10px var(--mono);letter-spacing:.1em;color:var(--muted);padding:0 4px 6px;position:sticky;top:0;background:var(--panel)}
.legend i{display:inline-block;width:9px;height:9px;border-radius:2px;margin:0 4px 0 12px;vertical-align:middle}.legend .ok{background:var(--good)}.legend .ab{background:var(--bad)}.legend .lim{background:var(--warn)}.legend .err{background:#c49bff}.legend{font-size:11px;color:var(--muted)}
.jh h3{margin:0;font-size:18px}.jh .sub{color:var(--muted);font:12px var(--mono);margin:4px 0 10px}.story{background:var(--panel2);border:1px solid var(--line);border-radius:8px;padding:10px 12px;color:#c3cdd8;font-size:13px}
.outcome{margin:12px 0;font:600 13px var(--mono)}.steps{margin-top:12px}.stp{display:grid;grid-template-columns:40px 190px minmax(0,1fr);gap:12px;padding:10px 0;border-top:1px solid #141b22}.stp .k{font:700 12px var(--mono);color:var(--dim)}
.stp img{width:190px;border-radius:6px;border:1px solid var(--line);cursor:zoom-in;display:block}.stp .noimg{width:190px;height:110px;border:1px dashed var(--line);border-radius:6px}
.e{overflow-wrap:anywhere;font-size:12.5px;margin:2px 0;padding:2px 6px;border-radius:4px}.e .ty{font:600 10px var(--mono);letter-spacing:.06em;color:var(--muted);margin-right:6px;text-transform:uppercase}.e .id{font:10px var(--mono);color:var(--dim);margin-left:6px}
.e.decision{color:var(--text)}.e.decision .r{color:#e7edf3}.e.abandon,.e.objection,.e.form_error,.e.page_error,.e.console_error,.e.http_error{color:#ffb3b3}.e.milestone,.e.goal_complete{color:var(--good)}.e.hl{background:#23301f;outline:1px solid var(--good)}
.url{font:11px var(--mono);color:var(--dim)}.caveats li{margin:6px 0;color:#c3cdd8}.foot{padding:18px 0 40px;font-size:11px}
.lightbox[hidden]{display:none}.lightbox{position:fixed;inset:0;background:rgba(0,0,0,.85);display:grid;place-items:center;z-index:20;cursor:zoom-out}.lightbox img{max-width:92vw;max-height:92vh;border-radius:8px}
@media(max-width:600px){.fr,.bl{grid-template-columns:1fr}.bl .rk{display:none}.bl .sc,.meter{text-align:left}.kpis{grid-template-columns:1fr}.auditors{grid-template-columns:1fr}.top .meta{display:none}}
@media(max-width:980px){.hero,.grid2,.explorer{grid-template-columns:1fr}.kpis{grid-template-columns:repeat(2,1fr)}.auditors{grid-template-columns:1fr 1fr}.roster{border:0;max-height:360px}.stp{grid-template-columns:32px 1fr}.stp .shot{grid-column:2}.stp img,.stp .noimg{width:100%}}
`;

/* Client script: plain ES5-style concatenation, no template literals (embedded in a TS template). */
const CLIENT = `
(function(){
var D=JSON.parse(document.getElementById('data').textContent);
var $=function(id){return document.getElementById(id)};
var h=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return '&#'+c.charCodeAt(0)+';'})};
var pct=function(v){return v==null?'—':Math.round(v*100)+'%'};
var C=D.comparison, V=D.summaries.map(function(s){return s.variant});
var B=C?C.baseline:V[0], K=C?C.candidate:V[0];
var sum=function(v){return D.summaries.filter(function(s){return s.variant===v})[0]};
function fmt(v,u){if(v==null)return '—';if(u==='pct')return pct(v);if(u==='ms')return v>=1000?(v/1000).toFixed(1)+'s':Math.round(v)+'ms';if(u==='steps')return (Math.round(v*10)/10)+'';return v.toFixed(2)}
function fd(v,u){if(v==null)return '—';var s=v>0?'+':v<0?'−':'±',a=Math.abs(v);if(u==='pct')return s+Math.round(a*100)+'pp';if(u==='ms')return s+(a>=1000?(a/1000).toFixed(1)+'s':Math.round(a)+'ms');if(u==='steps')return s+(Math.round(a*10)/10);return s+a.toFixed(2)}
function ev(id){return '<a class="ev" data-ev="'+h(id)+'" title="Open journey at this event">'+h(id)+'</a>'}
$('meta').textContent='session '+D.meta.session+' · '+D.meta.buyer+' buyers · seed '+D.meta.seed+' · '+new Date(D.meta.generated).toLocaleString();

// HERO
var heroL='<div><div class="count"><b>'+D.meta.buyers+'</b> BUYERS <span>·</span> <b>'+D.meta.segments+'</b> SEGMENTS <span>·</span> <b>'+V.length+'</b> VARIANT'+(V.length>1?'S':'')+'</div>'+
 (C?'<div class="vs"><span class="b">'+h(B.toUpperCase())+'</span> → <span class="c">'+h(K.toUpperCase())+'</span></div>':'<div class="vs">'+h(V.join(', ').toUpperCase())+'</div>')+
 '<div style="margin-top:14px"><span class="badge proxy">CONVERSION PROXY</span>'+(C?'<span class="badge">'+h(C.label)+'</span>':'')+'</div></div>';
var heroR='';
if(C){var hd=C.headline;heroR='<div class="headline"><h2>Goal completion delta</h2><div class="big'+(hd.delta<0?' neg':'')+'">'+fd(hd.delta,'pct')+'</div><div class="dim mono" style="margin-top:8px">'+pct(sum(B).completion.rate)+' → '+pct(sum(K).completion.rate)+' · 95% interval '+fd(hd.lo,'pct')+' … '+fd(hd.hi,'pct')+' · n='+C.n_pairs+' paired buyers</div><div class="dim mono" style="margin-top:6px">'+C.discordant.gained+' buyer(s) flipped fail → complete · '+C.discordant.lost+' flipped complete → fail</div></div>'}
else{var s0=sum(K);heroR='<div class="headline"><h2>Goal completion</h2><div class="big">'+pct(s0.completion.rate)+'</div><div class="dim mono" style="margin-top:8px">95% Wilson '+pct(s0.completion.lo)+' … '+pct(s0.completion.hi)+' · n='+s0.n+'</div></div>'}
$('hero').innerHTML=heroL+heroR;

// KPIs
var kp=[['Goal completion','completion'],['Abandonment','abandonment'],['Friction / buyer','friction'],['Runs with errors','errors'],['Median steps','steps']];
function kv(v,key){var s=sum(v);if(key==='completion')return[s.completion.rate,'pct'];if(key==='abandonment')return[s.abandonment.rate,'pct'];if(key==='friction')return[s.friction_events_per_buyer,'count'];if(key==='errors')return[s.error_rate.rate,'pct'];return[s.median_steps,'steps']}
var rowFor={completion:'Goal completion',abandonment:'Abandonment',friction:'Friction events / buyer',errors:'Runs with browser errors',steps:'Median steps (all journeys)'};
$('kpis').innerHTML=kp.map(function(k){var b=kv(B,k[1]),c=kv(K,k[1]);var r=C?C.rows.filter(function(x){return x.metric===rowFor[k[1]]})[0]:null;
 var cls=r?(r.verdict==='improved'?'good':r.verdict==='regressed'?'bad':'flat'):'flat';
 return '<div class="kpi"><div class="l">'+k[0]+'</div><div class="v">'+(C?'<span class="b">'+fmt(b[0],b[1])+'</span><span class="arrow">→</span>':'')+fmt(c[0],c[1])+'</div>'+
 (r?'<div class="d '+cls+'">'+fd(r.delta,r.unit)+' <span class="dim" style="font-weight:400">'+r.verdict+'</span></div>'+(r.ci?'<div class="ci">95% '+fd(r.ci[0],r.unit)+' … '+fd(r.ci[1],r.unit)+'</div>':'<div class="ci">median</div>'):'')+'</div>'}).join('');

// FUNNEL
var st=sum(K).funnel.map(function(f){return f.stage});
$('funnel').innerHTML=st.map(function(stage,i){var fb=sum(B).funnel[i],fc=sum(K).funnel[i];
 return '<div class="fun"><div>'+h(stage.replace(/_/g,' '))+'</div><div class="bars">'+(C?'<div class="bar"><i class="b" style="width:'+(fb.rate*100)+'%"></i></div>':'')+'<div class="bar"><i class="c" style="width:'+(fc.rate*100)+'%"></i></div></div><div class="n">'+(C?pct(fb.rate)+'<br>':'')+pct(fc.rate)+'</div></div>'}).join('')+
 (C?'<div class="legend mono" style="margin-top:8px"><i style="background:var(--base)"></i>'+h(B)+' <i style="background:var(--cand)"></i>'+h(K)+'</div>':'');

// SEGMENTS
var segs=sum(K).segments;
$('segments').innerHTML='<table><thead><tr><th>Segment</th><th>n</th>'+(C?'<th class="num">'+h(B)+'</th>':'')+'<th class="num">'+h(K)+'</th>'+(C?'<th class="num">Δ</th>':'')+'</tr></thead><tbody>'+
 segs.map(function(s){var sb=C?sum(B).segments.filter(function(x){return x.archetype===s.archetype})[0]:null;var d=sb?s.completion.rate-sb.completion.rate:0;
 return '<tr><td><b>'+h(s.segment)+'</b><div class="url">'+h(s.archetype)+(s.top_abandon_reason&&s.completed<s.n?' · exit: '+h(s.top_abandon_reason.slice(0,70)):'')+'</div></td><td class="num">'+s.n+'</td>'+(C?'<td class="num">'+(sb?pct(sb.completion.rate):'—')+'</td>':'')+'<td class="num">'+pct(s.completion.rate)+'</td>'+(C?'<td class="num '+(d>0?'good':d<0?'bad':'flat')+'">'+fd(d,'pct')+'</td>':'')+'</tr>'}).join('')+'</tbody></table>';

// FRICTION
function renderFriction(v){var diff=C?C.friction:[];var cl=D.clusters.filter(function(c){return c.variant===v});
 if(!cl.length){$('friction').innerHTML='<p class="dim">No friction signals detected.</p>';return}
 $('friction').innerHTML=cl.map(function(c){var d=diff.filter(function(x){return x.code===c.code})[0];var status=d&&v===K?d.status:null;
  return '<div class="fr"><div><h3>'+h(c.title)+' '+(status?'<span class="chip '+status+'">'+status.toUpperCase()+'</span>':'')+'<span class="chip '+c.severity+'">'+c.severity+'</span></h3>'+
  '<div>'+Object.keys(c.segments).map(function(s){return '<span class="chip">'+h(s)+' · '+c.segments[s]+'</span>'}).join('')+'</div>'+
  (c.examples[0]?'<div class="ex">“'+h(c.examples[0].slice(0,180))+'”</div>':'')+'<div>'+c.evidence_ids.slice(0,6).map(ev).join('')+(c.evidence_ids.length>6?'<span class="dim mono" style="font-size:11px"> +'+(c.evidence_ids.length-6)+' more</span>':'')+'</div></div>'+
  '<div class="meter"><b>'+c.affected+'</b>/'+c.population+' buyers<br><span class="dim">'+c.blocking_runs+' ended their journey here</span><div class="bar"><i style="width:'+(c.affected/c.population*100)+'%"></i></div></div></div>'}).join('');
 if(C&&v===K){var res=D.resolved;if(res.length)$('friction').innerHTML+='<div class="fr"><div><h3>Resolved vs '+h(B)+'</h3>'+res.map(function(r){return '<span class="chip resolved">'+h(r.title)+' · '+r.baseline_affected+' → 0</span>'}).join('')+'</div><div></div></div>'}}
function tabs(el,fn,init){$(el).innerHTML=V.map(function(v){return '<button class="tab'+(v===init?' on':'')+'" data-v="'+h(v)+'">'+h(v)+'</button>'}).join('');
 $(el).onclick=function(e){var b=e.target.closest('button');if(!b)return;[].forEach.call($(el).children,function(x){x.classList.toggle('on',x===b)});fn(b.getAttribute('data-v'))};fn(init)}
tabs('frictionTabs',renderFriction,K);

// BACKLOG
$('blv').textContent=D.backlog_variant;$('formula').textContent=D.meta.formula;
$('backlog').innerHTML=D.backlog.length?D.backlog.map(function(o){var f=o.factors;
 return '<div class="bl"><div class="rk">#'+o.rank+'</div><div><h3>'+h(o.title)+' '+(o.status?'<span class="chip '+o.status+'">'+o.status.toUpperCase()+'</span>':'')+'<span class="chip '+(o.claim==='inference'?'inference':'hypothesis')+'">'+o.claim.toUpperCase()+'</span></h3>'+
 '<div class="exp">'+h(o.experiment)+'</div><div class="fx">if fixed: up to +'+Math.round(o.ceiling_pp*100)+'pp goal completion (journeys that ended here) · affected '+o.affected+' · severity '+f.severity+' · goal impact '+f.goal_impact.toFixed(2)+' · confidence '+f.confidence+' · effort '+f.effort+' · reversibility '+f.reversibility+' · testability '+f.testability+'</div><div style="margin-top:6px">'+o.evidence_ids.slice(0,4).map(ev).join('')+'</div></div>'+
 '<div class="sc"><b>'+o.score+'</b><span class="lev '+o.leverage.split(' ')[0]+'">'+h(o.leverage)+'</span></div></div>'}).join(''):'<p class="dim">No actionable friction with evidence.</p>';

// AUDITORS
var AUD=[['ux','UX / usability','Can buyers find and operate it?'],['business','Business / conversion','Where does the funnel leak?'],['engineering','Engineering / reliability','Did the product behave?'],['customer','Customer / objections','What stopped buyers?'],['redteam','Skeptical red team','What is weaker than it looks?']];
function renderAudit(v){var au=D.audits[v];if(!au)return;
 $('auditors').innerHTML=AUD.map(function(a){var n=au.findings.filter(function(f){return f.auditor===a[0]}).length;var dg=au.degraded.filter(function(d){return d.auditor===a[0]})[0];
  return '<div class="aud'+(a[0]==='redteam'?' red':'')+'"><div class="t">'+a[1]+'</div><div class="n">'+n+'</div><p>'+a[2]+'</p>'+(dg?'<div class="deg">degraded → deterministic</div>':'')+'</div>'}).join('');
 $('consensus').innerHTML='<div class="dim mono" style="font-size:11px;margin-bottom:6px">auditors: '+h(au.auditor_mode)+' · '+au.consensus.length+' consensus items · '+au.rejected.length+' findings rejected for missing evidence</div>'+
  au.consensus.map(function(c){return '<div class="cs"><h3><span class="mono dim">'+h(c.id)+'</span> '+h(c.title)+' <span class="chip '+c.severity+'">'+c.severity+'</span><span class="chip">confidence '+c.confidence+'</span></h3>'+
  '<div class="fact"><span class="chip fact">OBSERVED FACT</span> '+h(c.observed_fact)+'</div>'+
  '<div class="interp"><span class="chip '+c.claim+'">'+c.claim.toUpperCase()+'</span> '+h(c.interpretation.replace(/^Likely cause \\([a-z]+\\): /,'Likely cause: '))+'</div>'+
  (c.counterfactual?'<div class="interp"><span class="chip fact">COUNTERFACTUAL</span> '+h(c.counterfactual)+'</div>':'')+
  '<div class="dim" style="font-size:12px">sources '+(c.sources||[]).map(function(s){return '<span class="chip">'+s+'</span>'}).join('')+' · auditors '+c.supporters.map(function(s){return '<span class="chip">'+s+'</span>'}).join('')+' · experiment: '+h(c.proposed_experiments[0]||'')+'</div>'+
  c.challenges.map(function(x){return '<div class="chal">RED TEAM: '+h(x.text)+'</div>'}).join('')+
  '<div style="margin-top:6px">'+c.evidence_ids.slice(0,5).map(ev).join('')+'</div></div>'}).join('')}
tabs('auditTabs',renderAudit,K);

// EXPLORER
var J=D.journeys, byP={};J.forEach(function(j){(byP[j.persona_id]=byP[j.persona_id]||{})[j.variant]=j});
var ids=Object.keys(byP).sort();
$('roster').innerHTML='<div class="rh"><span>BUYER</span>'+V.map(function(v){return '<span>'+h(v.slice(0,9).toUpperCase())+'</span>'}).join('')+'</div>'+ids.map(function(id){var any=byP[id][V[0]]||byP[id][V[1]];
 return '<div class="rr"><div class="who"><b>'+h(any.name)+'</b><span>'+h(any.segment)+' · '+h(id)+'</span></div>'+V.map(function(v){var j=byP[id][v];return j?'<button class="st-'+j.status+'" data-run="'+h(j.run_id)+'" title="'+h(j.status)+'">'+(j.completed?'✓ ':'✗ ')+j.steps+'</button>':'<span></span>'}).join('')+'</div>'}).join('');
$('roster').onclick=function(e){var b=e.target.closest('button[data-run]');if(b)openRun(b.getAttribute('data-run'))};
function openRun(runId,evId){var j=J.filter(function(x){return x.run_id===runId})[0];if(!j)return;
 [].forEach.call(document.querySelectorAll('.rr button'),function(b){b.classList.toggle('sel',b.getAttribute('data-run')===runId)});
 var steps={};j.events.forEach(function(e){(steps[e.step]=steps[e.step]||[]).push(e)});
 var out='<div class="jh"><h3>'+h(j.name)+' <span class="chip">'+h(j.variant)+'</span><span class="chip st-'+j.status+'">'+h(j.status)+'</span></h3><div class="sub">'+h(j.segment)+' · '+h(j.device)+' · budget '+h(j.budget)+' · '+h(j.run_id)+' · policy '+h(j.policy)+'</div>'+
  (j.story?'<div class="story">'+h(j.story)+'</div>':'')+'<div class="outcome '+(j.completed?'good':'bad')+'">'+(j.completed?'✓ Goal completed in '+j.steps+' steps':'✗ '+h(j.abandon_reason||j.status)+' (step '+j.steps+')')+'</div>'+
  (j.trace?'<div class="url">Playwright trace: <a href="'+h(j.trace)+'">'+h(j.trace)+'</a> — open with <code>npx playwright show-trace '+h(j.trace)+'</code></div>':'')+'</div><div class="steps">';
 Object.keys(steps).map(Number).sort(function(a,b){return a-b}).forEach(function(s){var es=steps[s];var shot=es.filter(function(e){return e.shot})[0];
  out+='<div class="stp"><div class="k">'+(s===0?'LAND':'#'+s)+'</div><div class="shot">'+(shot?'<img loading="lazy" src="'+h(shot.shot)+'" alt="Screenshot at step '+s+'">':(s===0?'':'<div class="noimg"></div>'))+'<div class="url">'+h((es[0]||{}).url||'')+'</div></div><div>'+
  es.filter(function(e){return e.type!=='observe'}).map(function(e){var txt=e.type==='decision'?'<span class="r">'+h(e.detail)+'</span>'+(e.target?' <span class="dim">→ '+h(e.target)+'</span>':''):h([e.target,e.detail].filter(Boolean).join(' — '));
   return '<div class="e '+e.type+(e.id===evId?' hl':'')+'" id="ev-'+h(e.id)+'"><span class="ty">'+h(e.type.replace(/_/g,' '))+'</span>'+txt+'<span class="id">'+h(e.id.split(':')[1])+'</span></div>'}).join('')+'</div></div>'});
 $('journey').innerHTML=out+'</div>';
 if(evId){var el=document.getElementById('ev-'+evId);if(el)el.scrollIntoView({block:'center'})}else $('explorer').scrollIntoView({block:'start'})}
document.addEventListener('click',function(e){var a=e.target.closest('[data-ev]');if(a){e.preventDefault();var id=a.getAttribute('data-ev');openRun(id.slice(0,id.lastIndexOf(':')),id)}
 var im=e.target.closest('.stp img');if(im){var lb=$('lightbox');lb.querySelector('img').src=im.src;lb.hidden=false}});
$('lightbox').onclick=function(){this.hidden=true};
var topEv=D.backlog[0]&&D.backlog[0].evidence_ids[0];var first=topEv?J.filter(function(j){return j.run_id===topEv.slice(0,topEv.lastIndexOf(':'))&&!j.completed})[0]:null;
first=first||J.filter(function(j){return j.variant===K&&!j.completed})[0]||J[0];if(first)openRun(first.run_id);window.scrollTo(0,0);

// CAVEATS
var cv=(C?C.caveats:['CONVERSION PROXY: synthetic goal completion is a behavioural proxy, not a prediction of real conversion or revenue.']).slice();
cv.push('Every finding cites event ids from recorded browser journeys; findings without valid evidence are rejected ('+Object.keys(D.audits).map(function(v){return v+': '+D.audits[v].rejected.length}).join(', ')+').');
cv.push('Rates use 95% Wilson intervals; variant deltas use a seeded paired bootstrap over personas.');
if(D.meta.usage&&D.meta.usage.length)cv.push('LLM usage: '+D.meta.usage.map(function(u){return u.provider+':'+u.model+' '+u.calls+' calls, '+u.input_tokens+' in / '+u.output_tokens+' out tokens, ≈$'+u.estimated_cost_usd.toFixed(4)}).join('; '));
else cv.push('No paid inference was used for this report (deterministic buyers and auditors).');
$('caveats').innerHTML=cv.map(function(x){return '<li>'+h(x)+'</li>'}).join('');
})();
`;
